# title: Long's blog
# tagline: Software Engineer
# author:
#   name: 'Long Tom'
# twitter: 
# Change 'comments' to true for Disqus comments
# disqus:
#   comments: false
#   disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/ngvlong'}
- {icon: 'twitter', link: 'https://twitter.com/ngvlongit1'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/ngvlongit1/'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
 
# pagination:
#   next_page: 'Mới hơn'
#   previous_page: 'Cũ hơn'

# sharing_button_prompt: 'Chia sẻ!'

# related_posts: 'Có thể bạn cũng thích:'

# post_date_prefix: 'Được viết vào '
